### ISSUE TITLE
Checklist before non alpha release

### ISSUE THREAD

**Issue by Lykrast** [Lykrast/DefiledLands#1]
- [x] Fix corruption during initial world gen
- [x] In game documentation (partial)
- [x] Sounds for Book Wyrms
- [ ] Original sounds for Shamblers
- [ ] Original sounds for The Destroyer
- [ ] Uses for Ravaging Essence
- [ ] The Overseer (before or after Blessed Seed ?)
- [ ] Blessed Seed (maybe will wait a bit)
